### ISSUE TITLE
Create one .yaml environment file per rule

### ISSUE THREAD

**Issue by mgalland** [KoesGroup/Snakemake_ChIPseq#10]
To increase reproducibility and avoid the need to install and activate a conda virtual environemnt before running Snakemake, it would be good to create one environment file per rule (envs/rule1.yaml) in order to use snakemake with the `--use-conda` argument.

**Comment by mgalland** [comment]
As this is a new feature, I would create a new branch with `git checkout -b issue-10`. Then if everything works well on that branch, it will be merged with the `develop` branch

**Comment by JihedC** [comment]
Done in the #7
